<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>JS的error处理</title>
</head>
<body>
    <script>
        /**
         * 目标：进一步理解JS中的错误（ERROR）和错误处理
         * 1.错误的类型
         *  Error:所有的错误的父类型
         *  ReferenceError:引用的变量不存在
         *  TypeError:数据类型不正确的错误
         *  RangeError:数据值不在其所允许的范围内
         *  SyntaxError:语法错误
         * 2.错误处理
         *  捕获错误:try...catch...
         *  抛出错误:throw error
         * 3.错误对象
         *  message属性:错误相关信息
         *  stack属性:函数调用栈记录信息
        */
        //1.常见的内置错误
        //1)ReferenceError:引用的变量不存在
        //console.log(a);//Uncaught ReferenceError: a is not defined

        //2)TypeError:数据类型不正确的错误
        //let b=null;
        //console.log(b.xxx);//Uncaught TypeError: Cannot read properties of null (reading 'xxx')
        //b={};
        //b.xxx();//Uncaught TypeError: b.xxx is not a function

        //3)RangeError:数据值不在其所允许的范围内
        // function fn(){
        //     fn();
        // }
        // fn();//Uncaught RangeError: Maximum call stack size exceeded

        //4)SyntaxError:语法错误
        //const c="""";//Uncaught SyntaxError: Unexpected string

        //2.处理错误
        //捕获错误：try...catch...
        // try{
        //     let b=null;
        //     console.log(b.xxx);
        //     console.log("出错之后2")
        // }catch(error){
        //     console.log(error.message);
        //     console.log(error.stack)
        // }
        // console.log("出错之后1");

        //抛出错误：throw error
        function something(){
            if(Date.now()%2==1){
                console.log("当前时间为奇数，可以执行任务");
            }else{//如果时间是偶数 抛出异常 由调用者来处理
                throw new Error("当前时间为偶数,无法执行任务");
            }
        }
        try{
            something()
        }catch(error){
            //进行一些处理
            console.log(error);
        }
    </script>
</body>
</html>